name: Docker Image CI

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

env:
  OPENSSL_VERSION: 4.0.0
  QUICK_BUILD: true

jobs:
  build:
    strategy:
      matrix:
        ubuntu_version: ["25.10", "26.04"]
        python_version: ["3.13.13", "3.14.4", "3.15.0b1"]
        arch: ["amd64", "arm64"]
    runs-on: ${{ matrix.arch == 'amd64' && 'ubuntu-latest' || 'ubuntu-26.04-arm' }}
    env:
      UBUNTU_VERSION: ${{ matrix.ubuntu_version }}
      PYTHON_VERSION: ${{ matrix.python_version }}
      ARCH: ${{ matrix.arch }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build the Docker image
        run: bash src/build_image.sh
      - name: Test the image
        run: bash src/test_image.sh
