name: Docker Image CI

on:
  push:
    branches: [main]

env:
  OPENSSL_VERSION: 3.0.7

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      ubuntu_version: ["22.04", "22.10"]
      python_version: ["3.10.8", "3.11.0", "3.12.0a2"]
    env:
      UBUNTU_VERSION: ${{ matrix.ubuntu_version }}
      PYTHON_VERSION: ${{ matrix.python_version }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: bash src/build_image.sh
      - name: Test the image
        run: bash src/test_image.sh
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the Image
        run: |
          UBUNTU_ADJECTIVE=$(bash src/ubuntu_adjective.sh --ubuntu=${UBUNTU_VERSION})
          docker push ${DOCKERHUB_USERNAME}/${UBUNTU_ADJECTIVE}-python:${PYTHON_VERSION}
      - name: Retag to major.minor only (e.g. impish-python:3.10)
        run: |
          UBUNTU_ADJECTIVE=$(bash src/ubuntu_adjective.sh --ubuntu=${UBUNTU_VERSION})
          docker tag ${DOCKERHUB_USERNAME}/${UBUNTU_ADJECTIVE}-python:${PYTHON_VERSION} ${DOCKERHUB_USERNAME}/${UBUNTU_ADJECTIVE}-python:${PYTHON_VERSION%.*}
          docker push ${DOCKERHUB_USERNAME}/${UBUNTU_ADJECTIVE}-python:${PYTHON_VERSION%.*}
