name: Docker Image CI

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

env:
  OPENSSL_VERSION: 3.3.2
  QUICK_BUILD: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu_version: ["22.04", "24.04"]
        python_version: ["3.11.10", "3.12.7", "3.13.0rc3"]
    env:
      UBUNTU_VERSION: ${{ matrix.ubuntu_version }}
      PYTHON_VERSION: ${{ matrix.python_version }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: bash src/build_image.sh
      - name: Test the image
        run: bash src/test_image.sh
